{
    'name': 'Odoo 18 Shopify Sync',
    'version': '18.0.1.0.0',
    'summary': 'Shopify to Odoo 18 One-way Integration',
    'description': 'Import Customers, Products, Sales Orders, and Payments from Shopify into Odoo.',
    'category': 'Sales',
    'author': 'GreenVision',
    'website': 'https://www.greenvision.in',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'sale',
        'sale_management',
        'stock',
        'account',
        'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/cron.xml',
        'views/menus.xml',
        'views/shopify_instance_views.xml',
        'views/shopify_sync_log_views.xml',
        'views/shopify_payment_views.xml',
        'views/sale_order_views.xml',
        'views/res_partner_views.xml',
        'views/product_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
